// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOr14azkK6KWtKdqGlLZLef180z2qmmI0',
    appId: '1:83581349290:web:e313d0469e9c82c69c0fd3',
    messagingSenderId: '83581349290',
    projectId: 'iot-ifa',
    authDomain: 'iot-ifa.firebaseapp.com',
    databaseURL: 'https://iot-ifa-default-rtdb.firebaseio.com',
    storageBucket: 'iot-ifa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM0gLtqcabYxepQdLiZE-0DRzPVHssiHQ',
    appId: '1:83581349290:android:ca75707210bec3dc9c0fd3',
    messagingSenderId: '83581349290',
    projectId: 'iot-ifa',
    databaseURL: 'https://iot-ifa-default-rtdb.firebaseio.com',
    storageBucket: 'iot-ifa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNWvXW9OMO9QzR8x9Bn9U66L7K2nlvan8',
    appId: '1:83581349290:ios:9ddc303ac2486db89c0fd3',
    messagingSenderId: '83581349290',
    projectId: 'iot-ifa',
    databaseURL: 'https://iot-ifa-default-rtdb.firebaseio.com',
    storageBucket: 'iot-ifa.firebasestorage.app',
    iosBundleId: 'com.example.agroflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNWvXW9OMO9QzR8x9Bn9U66L7K2nlvan8',
    appId: '1:83581349290:ios:9ddc303ac2486db89c0fd3',
    messagingSenderId: '83581349290',
    projectId: 'iot-ifa',
    databaseURL: 'https://iot-ifa-default-rtdb.firebaseio.com',
    storageBucket: 'iot-ifa.firebasestorage.app',
    iosBundleId: 'com.example.agroflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOr14azkK6KWtKdqGlLZLef180z2qmmI0',
    appId: '1:83581349290:web:5092ed79d71332639c0fd3',
    messagingSenderId: '83581349290',
    projectId: 'iot-ifa',
    authDomain: 'iot-ifa.firebaseapp.com',
    databaseURL: 'https://iot-ifa-default-rtdb.firebaseio.com',
    storageBucket: 'iot-ifa.firebasestorage.app',
  );
}
